import type { Metadata } from 'next';
import { Doto, Montserrat } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout';
import { AuthProvider } from '@/components/common';
import { LoginModalProvider } from '@/context';

const doto = Doto({
  subsets: ['latin'],
  variable: '--font-logo',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${doto.variable} ${montserrat.variable} antialiased`}>
        <AuthProvider>
          <LoginModalProvider>
            <Header />
            {children}
          </LoginModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
