import type { Metadata } from "next";
import { Doto, Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout";

const doto = Doto({
  subsets: ["latin"],
  variable: "--font-logo",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${doto.variable} ${montserrat.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
